name: html_imports
dependencies:
  browser: '^0.10.0'
  initialize: any
  web_components:
    path: '../../'
dev_dependencies:
  unittest: '^0.11.0'
transformers:
- web_components:
    $include: '**/*_test.html'
    entry_points: test/basic_test.html
